# Generated by Django 5.2.13 on 2026-04-22 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0007_backfill_partners"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(default="Home", max_length=120)),
                ("slug", models.SlugField(max_length=120)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Shown at /dashboard when no slug is specified.",
                    ),
                ),
                (
                    "industry_preset",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tracks which industry YAML preset seeded this dashboard. Lets us re-seed a tenant's default dashboard after a preset bump.",
                        max_length=60,
                    ),
                ),
                (
                    "layout_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Positions / sizes when we add drag-to-rearrange (future).",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("kpi", "KPI tile (big number + optional detail)"),
                            ("bar", "Bar chart"),
                            ("line", "Line chart"),
                            ("pie", "Pie chart"),
                            ("area", "Area chart"),
                            ("table", "Ranked list / table"),
                        ],
                        default="kpi",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("subtitle", models.CharField(blank=True, default="", max_length=240)),
                (
                    "data_source",
                    models.CharField(
                        help_text="Registry key — see modules.dashboards.data_sources. Not user-editable raw SQL; always a whitelisted aggregate.",
                        max_length=120,
                    ),
                ),
                (
                    "config_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Widget-type-specific config plus data-source parameters. Shape examples: {"period": "last_30_days", "limit": 5}.',
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="dashboards.dashboard",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["dashboard", "position", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="dashboard",
            constraint=models.UniqueConstraint(
                fields=("company", "slug"), name="dashboard_company_slug_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("company",),
                name="dashboard_company_one_default",
            ),
        ),
    ]
