# Generated by Django 5.2.13 on 2026-04-16 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_partner"),
        ("purchasing", "0002_requestforquote_rfqline"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.partner",
            ),
        ),
    ]
