# Generated by Django 5.2.13 on 2026-04-18 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_module", "0001_initial"),
        ("core", "0007_backfill_partners"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="external_uid",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="External UID from CRM calendar sync (RFC 5545 UID)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("external_uid__isnull", False),
                    models.Q(("external_uid", ""), _negated=True),
                ),
                fields=("company", "external_uid"),
                name="calendar_event_company_external_uid_uniq",
            ),
        ),
    ]
