# Generated by Django 5.2.13 on 2026-04-12 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codename", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("module", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["module", "action"],
            },
        ),
        migrations.CreateModel(
            name="IndustryRoleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("fintech", "FinTech"),
                            ("healthcare", "Healthcare"),
                            ("insurance", "Insurance"),
                            ("real_estate", "Real Estate"),
                            ("logistics", "Logistics"),
                            ("dental", "Dental Clinic"),
                            ("legal", "Legal Firm"),
                            ("hospitality", "Hospitality/Restaurant"),
                            ("construction", "Construction"),
                            ("education", "Education"),
                        ],
                        max_length=20,
                    ),
                ),
                ("role_slug", models.SlugField(max_length=100)),
                ("role_name", models.CharField(max_length=255)),
                (
                    "role_level",
                    models.CharField(
                        choices=[
                            ("L1", "Operational"),
                            ("L2", "Supervisor"),
                            ("L3", "Manager"),
                            ("L4", "Director"),
                            ("L5", "Executive"),
                        ],
                        max_length=2,
                    ),
                ),
                ("module_permissions", models.JSONField(default=list)),
                ("dashboard_config", models.JSONField(blank=True, default=dict)),
                ("anomaly_alerts", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["industry", "role_level", "role_name"],
                "unique_together": {("industry", "role_slug")},
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("is_system", models.BooleanField(default=False)),
                (
                    "role_level",
                    models.CharField(
                        choices=[
                            ("L1", "Operational"),
                            ("L2", "Supervisor"),
                            ("L3", "Manager"),
                            ("L4", "Director"),
                            ("L5", "Executive"),
                        ],
                        max_length=2,
                    ),
                ),
                ("dashboard_config", models.JSONField(blank=True, default=dict)),
                ("anomaly_alerts", models.JSONField(blank=True, default=list)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_roles",
                        to="core.industryroletemplate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="core.role",
                    ),
                ),
            ],
            options={
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                through="core.RolePermission",
                to="core.permission",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("company", "name")},
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="core.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "role")},
            },
        ),
    ]
