# Generated by Django 5.2.13 on 2026-04-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_viewdefinition"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryConfigTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("fintech", "FinTech"),
                            ("healthcare", "Healthcare"),
                            ("insurance", "Insurance"),
                            ("real_estate", "Real Estate"),
                            ("logistics", "Logistics"),
                            ("dental", "Dental Clinic"),
                            ("legal", "Legal Firm"),
                            ("hospitality", "Hospitality/Restaurant"),
                            ("construction", "Construction"),
                            ("education", "Education"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Full config dict including terminology, module overrides, and defaults.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["industry"],
            },
        ),
    ]
