# Generated by Django 5.2.13 on 2026-04-26 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_backfill_partners"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyWebhookConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peer_url",
                    models.URLField(
                        help_text="Where outbound webhooks are POSTed. Example: https://crm.novapay.com/api/v1/webhooks/calendar/novapay/",
                        max_length=500,
                    ),
                ),
                (
                    "shared_secret",
                    models.CharField(
                        help_text="32+ byte hex key shared with the peer. Used for HMAC sign + verify.",
                        max_length=128,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="When False, both inbound and outbound webhooks are no-ops.",
                    ),
                ),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_config",
                        to="core.company",
                    ),
                ),
            ],
        ),
    ]
